package tw.com.rex.service.product;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-10T17:49:25.671+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "ProductWebServiceImplService", 
                  wsdlLocation = "http://purchaseorderservice.azurewebsites.net/PurchaseOrderService_20160510/ProductService?wsdl",
                  targetNamespace = "http://impl.service.web.com.tw/") 
public class ProductWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.web.com.tw/", "ProductWebServiceImplService");
    public final static QName ProductWebServiceImplPort = new QName("http://impl.service.web.com.tw/", "ProductWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://purchaseorderservice.azurewebsites.net/PurchaseOrderService_20160510/ProductService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProductWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://purchaseorderservice.azurewebsites.net/PurchaseOrderService_20160510/ProductService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProductWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ProductWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ProductWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ProductWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ProductWebService
     */
    @WebEndpoint(name = "ProductWebServiceImplPort")
    public ProductWebService getProductWebServiceImplPort() {
        return super.getPort(ProductWebServiceImplPort, ProductWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductWebService
     */
    @WebEndpoint(name = "ProductWebServiceImplPort")
    public ProductWebService getProductWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(ProductWebServiceImplPort, ProductWebService.class, features);
    }

}
