package tw.com.rex.service.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-10T17:48:35.067+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://service.web.com.tw/", name = "UserWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserWebService {

    @WebMethod
    @RequestWrapper(localName = "insert", targetNamespace = "http://service.web.com.tw/", className = "tw.com.rex.service.user.Insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://service.web.com.tw/", className = "tw.com.rex.service.user.InsertResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String insert(
        @WebParam(name = "user", targetNamespace = "")
        tw.com.rex.service.user.User user
    );

    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://service.web.com.tw/", className = "tw.com.rex.service.user.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://service.web.com.tw/", className = "tw.com.rex.service.user.UpdateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String update(
        @WebParam(name = "user", targetNamespace = "")
        tw.com.rex.service.user.User user
    );

    @WebMethod
    @RequestWrapper(localName = "checkDuplicate", targetNamespace = "http://service.web.com.tw/", className = "tw.com.rex.service.user.CheckDuplicate")
    @ResponseWrapper(localName = "checkDuplicateResponse", targetNamespace = "http://service.web.com.tw/", className = "tw.com.rex.service.user.CheckDuplicateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String checkDuplicate(
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email
    );

    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://service.web.com.tw/", className = "tw.com.rex.service.user.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.web.com.tw/", className = "tw.com.rex.service.user.DeleteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String delete(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @WebMethod
    @RequestWrapper(localName = "login", targetNamespace = "http://service.web.com.tw/", className = "tw.com.rex.service.user.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.web.com.tw/", className = "tw.com.rex.service.user.LoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String login(
        @WebParam(name = "user", targetNamespace = "")
        tw.com.rex.service.user.User user
    );

    @WebMethod
    @RequestWrapper(localName = "logout", targetNamespace = "http://service.web.com.tw/", className = "tw.com.rex.service.user.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://service.web.com.tw/", className = "tw.com.rex.service.user.LogoutResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String logout(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId
    );
}
