package tw.com.rex.service.user;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-10T17:48:35.103+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "UserWebServiceImplService", 
                  wsdlLocation = "http://purchaseorderservice.azurewebsites.net/PurchaseOrderService_20160510/UserService?wsdl",
                  targetNamespace = "http://impl.service.web.com.tw/") 
public class UserWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.web.com.tw/", "UserWebServiceImplService");
    public final static QName UserWebServiceImplPort = new QName("http://impl.service.web.com.tw/", "UserWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://purchaseorderservice.azurewebsites.net/PurchaseOrderService_20160510/UserService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://purchaseorderservice.azurewebsites.net/PurchaseOrderService_20160510/UserService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UserWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UserWebService
     */
    @WebEndpoint(name = "UserWebServiceImplPort")
    public UserWebService getUserWebServiceImplPort() {
        return super.getPort(UserWebServiceImplPort, UserWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserWebService
     */
    @WebEndpoint(name = "UserWebServiceImplPort")
    public UserWebService getUserWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(UserWebServiceImplPort, UserWebService.class, features);
    }

}
